### ISSUE TITLE
Where is the fucking README?

### ISSUE THREAD

**Issue by f-prime** [wmww/define_EVIL#1]
I can't tell how immoral this is without a README, William.

EDIT: You don't get a star until I get a README.

**Comment by wmww** [comment]
Give me a fucking minute!

**Comment by wmww** [comment]
I was _going_ to write the readme and clean up before I pushed, but I had to transfer between computers. Didn't expect to have an active community this fast.

**Comment by f-prime** [comment]
You have to plan for the unexpected.

**Comment by wmww** [comment]
Happy now?
